"""init

Revision ID: f899a5e5a9c9
Revises: 
Create Date: 2026-04-21 17:30:53.770433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f899a5e5a9c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platformitemfilterlink')
    op.drop_table('platform')
    op.drop_table('platformitem')
    op.drop_table('filter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platformitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('transcript', sa.VARCHAR(), nullable=False),
    sa.Column('platform_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platformitemfilterlink',
    sa.Column('platform_item_id', sa.INTEGER(), nullable=False),
    sa.Column('filter_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filter.id'], ),
    sa.ForeignKeyConstraint(['platform_item_id'], ['platformitem.id'], ),
    sa.PrimaryKeyConstraint('platform_item_id', 'filter_id')
    )
    # ### end Alembic commands ###
